---
name: kalzium
version: 17.08.1
summary: KDE Periodic Table of Elements
description: Kalzium is a program that shows you the Periodic Table of Elements. You
    can use Kalzium to search for information about the elements or to learn facts
    about the periodic table. It provides an overview of the important data (like
    melting points, electron affinity, electron negativity, electron configuration,
    radii, mass, ionisation energy), an isotope table, and different colored views
    of the periodic table (separation of the different blocks, year simulator, temperature
    simulator). It contains tools to visualize the spectral lines of each element,
    a molecular weight calculator, a 3D molecule editor, and an equation solver for
    stoichiometric problems.
confinement: strict
grade: stable
apps:
    kalzium:
        command: kf5-launch kalzium
        plugs:
        - kde-frameworks-5-plug
        - home
        - x11
        - opengl
        - network
        - network-bind
        - unity7
        - pulseaudio
plugs:
    kde-frameworks-5-plug:
        content: kde-frameworks-5-all
        interface: content
        default-provider: kde-frameworks-5
        target: kf5
parts:
    kalzium:
        after:
        - kde-frameworks-5-dev
        - kde-frameworks-5-env
        plugin: cmake
        build-packages:
        - chemical-mime-data
        - libboost-python-dev
        - libeigen3-dev
        - libfacile-ocaml-dev
        - libglew-dev
        - libkf5doctools-dev
        - libkf5kdelibs4support-dev
        - libkf5khtml-dev
        - libopenbabel-dev
        - libsm-dev
        - libsoprano-dev
        - pkg-config
        - libpulse0
        source: https://download.kde.org/stable/applications/17.08.1/src/kalzium-17.08.1.tar.xz
        configflags:
        - "-DKDE_INSTALL_USE_QT_SYS_PATHS=ON"
        - "-DCMAKE_INSTALL_PREFIX=/usr"
        - "-DCMAKE_BUILD_TYPE=Release"
        - "-DENABLE_TESTING=OFF"
        - "-DBUILD_TESTING=OFF"
        - "-DKDE_SKIP_TEST_SETTINGS=ON"
